import java.util.Scanner;
 public class ExceptionDemo 
{

	public static void main(String[] args) 
	{
		
		Scanner sc=new Scanner(System.in);
		System.out.println("enter first value ");
		int a=sc.nextInt();
		System.out.println("second value");
		int b=sc.nextInt();
		int c= a+b;
		System.out.println("c="+c);
	
		// TODO Auto-generated method stub
      /* int e=10,f=0,h;

      /* Scanner cin=new Scanner(System.in);
       System.out.println("enter e,f");
       e=cin.nextInt();
       f=cin.nextInt();*/
     /* try
       {
    	   String str="hello";
    	   System.out.println(str.charAt(2));
    	   h=e/f;
    	   System.out.println("the quotient is:"+h);
       }
       catch(java.lang.ArithmeticException obj)                                                                                                        
       {
    	   System.out.println("the error is:"+obj);
       }
      finally
      {
      System.out.println("finally");
      }
      System.out.println("hello java");
       System.out.println("exception handling");*/
	}

}
